import DashboardLayout from '@/components/layouts/dashboard/DashboardLayout'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html>
			<body>
				<DashboardLayout>{children}</DashboardLayout>
			</body>
		</html>
	)
}
